# site settings
title: "ENGL 1450"
subtitle: "Reading and Writing in the Digital Age"
email: "r.cordell@northeastern.edu"
description: "A first-year course at Northeastern University."
baseurl: "/" 
url: "http://f18rwda.ryancordell.org"
author: "Ryan Cordell"
street_address: "Nightingale Hall 415, Northeastern University"
city: "Boston"
state: "MA"
zip_code: "02115"
country: "United States of America"
phone: 

# homepage tiles
tiles-source: pages # accepts "pages" or "posts"
tiles-count: 6

# contact form settings
form_url: https://formspree.io/r.cordell@northeastern.edu # endpoint URL to receive contact form submissions
form_email_name: _replyto # value of the "name" attribute in the "email" field

# social settings
500px_url:
facebook_url:
github_url: https://github.com/rccordell/f18rwda/tree/gh-pages
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed